[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "ppln-template"
version = "0.0.0"
dependencies = [
  'pandas',
  'pydmr',
]

[tool.setuptools.packages.find]
where = ["src"]